services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: RCE_Gateway
    ports:
      - "5101:8080"
    volumes:
      - ./certs:/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Endpoints__Https__Url=https://*:8080
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Password=RCE
    networks:
      - rce_network

  auth:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: RCE_Auth
    ports:
      - "5102:8080"
    volumes:
      - ./certs:/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Endpoints__Https__Url=https://*:8080
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Password=RCE
    networks:
      - rce_network
    depends_on:
      - postgres

  heroui:
    build:
      context: ./RCE_HeroUI
      dockerfile: Dockerfile.dev
    volumes:
      - ./RCE_HeroUI:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - rce_network

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: AdminPostgresPassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./dbInit:/docker-entrypoint-initdb.d
    networks:
      - rce_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: rce_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - rce_network
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres

  providers:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: RCE_Providers
    ports:
      - "5103:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - rce_network

networks:
  rce_network:


volumes:
  postgres-data:
