services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: RCE_Gateway
    ports:
      - "5101:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  auth:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: RCE_Auth
    ports:
      - "5102:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
